### ISSUE TITLE
How were the item/user state files created?

### ISSUE THREAD

**Issue by totoro234** [weitianxin/CLOVER#1]
How were the item_user_cold_state.json etc.. files created and what do they represent?

**Comment by weitianxin** [comment]
Thanks for your question. For the ML1M data set, we used the same data in the original MeLU code (except we have an additional validation set). For the other two data sets, we follow the same data preprocessing split strategy. In the ml100k/bx data folder, we have the preprocess.py that creates the files.

item_user_cold_state.json represents the interacted items of the new user. The format is {used_id: [item_0,  item_1, ...]}. 

item_user_cold_state_y.json represents the ratings of the interacted items. The format is {used_id: [rating_item_0,  rating_item_1, ...]}.
